version: 2

updates:
  # Package manager dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "jakubkunert"
    assignees:
      - "jakubkunert"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
    open-pull-requests-limit: 10

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    reviewers:
      - "jakubkunert"
    assignees:
      - "jakubkunert"
    commit-message:
      prefix: "chore(actions)"
    open-pull-requests-limit: 5
