name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1

    - name: Install dependencies
      run: bun install

    - name: Build project
      run: bun run build

    - name: Run tests
      run: bun run test

    - name: Extract version
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Version: $VERSION"

    - name: Generate release notes
      id: release_notes
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        echo "Generating release notes for $VERSION"

        # Create basic release notes
        cat > release_notes.txt << EOF
        # PolarisAI $VERSION

        ## What's New
        - Multi-agent AI reasoning system
        - Support for OpenAI and Ollama providers
        - TypeScript-first architecture
        - Comprehensive development workflow

        ## Installation
        \`\`\`bash
        git clone https://github.com/jakubkunert/PolarisAI.git
        cd PolarisAI
        bun install
        bun dev
        \`\`\`

        See the [README](https://github.com/jakubkunert/PolarisAI#readme) for full documentation.
        EOF

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: PolarisAI ${{ steps.version.outputs.version }}
        body_path: release_notes.txt
        draft: false
        prerelease: ${{ contains(steps.version.outputs.version, '-') }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ steps.version.outputs.version }}
        path: .next/
